### ISSUE TITLE
Copy Groovy Docs on publish

### ISSUE THREAD

**Issue by marcolink** [wooga/atlas-plugins#1]
copy or publish doc files to the final destination

**Comment by Larusso** [comment]
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Groovydoc.html

We have a few options to set.

**Comment by Larusso** [comment]
@marcolink https://dzone.com/articles/groovy-goodness-customize-groovydoc-output-with-gr something for you.
