### ISSUE TITLE
make integrationTest depend on test sourceset

### ISSUE THREAD

**Issue by Larusso** [wooga/atlas-plugins#56]
I produced a bug when upgrading to gradle 6.9. The integrationTest souceset can no longer access the sourceset of test.
It only has a dependency to it's dependencies. A short google search pointed me to this [SO](https://stackoverflow.com/a/18141700/1380824) anser which suggests to set
this dependency `integrationTestImplementation sourceSets.test.output`

This works locally for me.
We should also add this here in a cleaner form

**Comment by Joaquimmnetto** [comment]
This was fixed in the PR [#63](https://github.com/wooga/atlas-plugins/pull/63). Closing issue.
